name: Daily News Generation

on:
  schedule:
    # यह क्रोन जॉब रोज़ाना 5:00 AM UTC (लगभग 10:30 AM IST) पर चलेगा
    - cron: '0 5 * * *'
  # Manually run action from GitHub UI
  workflow_dispatch:

jobs:
  run_scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      
      - name: Run Scheduler Script
        env:
          # Vercel Environment Variables को यहां पास करना होगा
          MONGO_URI: ${{ secrets.MONGO_URI }}
          LLM_API_KEY: ${{ secrets.EMERGENT_LLM_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
        
        run: python backend/scheduler.py
